# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_twslink2pt', [dirname(__file__)])
        except ImportError:
            import _twslink2pt
            return _twslink2pt
        if fp is not None:
            try:
                _mod = imp.load_module('_twslink2pt', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _twslink2pt = swig_import_helper()
    del swig_import_helper
else:
    import _twslink2pt
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def GetErrorStringStdDLLWrap(dwError=0):
  return _twslink2pt.GetErrorStringStdDLLWrap(dwError)
GetErrorStringStdDLLWrap = _twslink2pt.GetErrorStringStdDLLWrap
tcDLLWrapX64Postfix = _twslink2pt.tcDLLWrapX64Postfix
class tcDllLoadcount(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, tcDllLoadcount, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, tcDllLoadcount, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _twslink2pt.new_tcDllLoadcount()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _twslink2pt.delete_tcDllLoadcount
    __del__ = lambda self : None;
    def count(self, *args): return _twslink2pt.tcDllLoadcount_count(self, *args)
    def decount(self, *args): return _twslink2pt.tcDllLoadcount_decount(self, *args)
    def get_count(self, *args): return _twslink2pt.tcDllLoadcount_get_count(self, *args)
    def HandShake(self): return _twslink2pt.tcDllLoadcount_HandShake(self)
tcDllLoadcount_swigregister = _twslink2pt.tcDllLoadcount_swigregister
tcDllLoadcount_swigregister(tcDllLoadcount)

class TWSLink2Wrap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TWSLink2Wrap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TWSLink2Wrap, name)
    __repr__ = _swig_repr
    def __init__(self, path=None, load=0): 
        this = _twslink2pt.new_TWSLink2Wrap(path, load)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _twslink2pt.delete_TWSLink2Wrap
    __del__ = lambda self : None;
    def dllname(self): return _twslink2pt.TWSLink2Wrap_dllname(self)
    def IsReady(self): return _twslink2pt.TWSLink2Wrap_IsReady(self)
    def GetError(self): return _twslink2pt.TWSLink2Wrap_GetError(self)
    def GetStrError(self): return _twslink2pt.TWSLink2Wrap_GetStrError(self)
    def GetLoaded(self): return _twslink2pt.TWSLink2Wrap_GetLoaded(self)
    def GetRefCount(self, lock=True): return _twslink2pt.TWSLink2Wrap_GetRefCount(self, lock)
    def GetHandle(self): return _twslink2pt.TWSLink2Wrap_GetHandle(self)
    def Load(self, expath=None): return _twslink2pt.TWSLink2Wrap_Load(self, expath)
    def Unload(self, code=0, bdeleteerror=1): return _twslink2pt.TWSLink2Wrap_Unload(self, code, bdeleteerror)
    def InternalLoad(self): return _twslink2pt.TWSLink2Wrap_InternalLoad(self)
    def InternalUnload(self): return _twslink2pt.TWSLink2Wrap_InternalUnload(self)
    __swig_getmethods__["InstanceCount"] = lambda x: _twslink2pt.TWSLink2Wrap_InstanceCount
    if _newclass:InstanceCount = staticmethod(_twslink2pt.TWSLink2Wrap_InstanceCount)
    def reset_pointer(self): return _twslink2pt.TWSLink2Wrap_reset_pointer(self)
    __swig_setmethods__["__pdll_count_map"] = _twslink2pt.TWSLink2Wrap___pdll_count_map_set
    __swig_getmethods__["__pdll_count_map"] = _twslink2pt.TWSLink2Wrap___pdll_count_map_get
    if _newclass:__pdll_count_map = _swig_property(_twslink2pt.TWSLink2Wrap___pdll_count_map_get, _twslink2pt.TWSLink2Wrap___pdll_count_map_set)
    def REGISTER_CONTRACT(self, *args): return _twslink2pt.TWSLink2Wrap_REGISTER_CONTRACT(self, *args)
    def REGISTER_CONTRACT2(self, *args): return _twslink2pt.TWSLink2Wrap_REGISTER_CONTRACT2(self, *args)
    def REGISTER_CONTRACT_XML(self, *args): return _twslink2pt.TWSLink2Wrap_REGISTER_CONTRACT_XML(self, *args)
    def REGISTER_CONTRACT_XML_STYLE(self, *args): return _twslink2pt.TWSLink2Wrap_REGISTER_CONTRACT_XML_STYLE(self, *args)
    def GET_CONTRACTUID_LIST(self, *args): return _twslink2pt.TWSLink2Wrap_GET_CONTRACTUID_LIST(self, *args)
    def WAIT_FOR_ACCEPTED(self, *args): return _twslink2pt.TWSLink2Wrap_WAIT_FOR_ACCEPTED(self, *args)
    def ADD_COMBO_LEG(self, *args): return _twslink2pt.TWSLink2Wrap_ADD_COMBO_LEG(self, *args)
    def REM_COMBO_LEG(self, *args): return _twslink2pt.TWSLink2Wrap_REM_COMBO_LEG(self, *args)
    def REQ_MARKET_DATA(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_MARKET_DATA(self, *args)
    def REQ_MARKET_DATA_TYPE(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_MARKET_DATA_TYPE(self, *args)
    def REQ_MARKET_DEPTH(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_MARKET_DEPTH(self, *args)
    def REQ_BAR_DATA(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_BAR_DATA(self, *args)
    def CANCEL_BAR_DATA(self, *args): return _twslink2pt.TWSLink2Wrap_CANCEL_BAR_DATA(self, *args)
    def GET_MARKET_DATA(self, *args): return _twslink2pt.TWSLink2Wrap_GET_MARKET_DATA(self, *args)
    def GET_BAR_DATA(self, *args): return _twslink2pt.TWSLink2Wrap_GET_BAR_DATA(self, *args)
    def GET_MARKET_DEPTH(self, *args): return _twslink2pt.TWSLink2Wrap_GET_MARKET_DEPTH(self, *args)
    def GET_MARKET_DEPTH2(self, *args): return _twslink2pt.TWSLink2Wrap_GET_MARKET_DEPTH2(self, *args)
    def GET_TICK(self, *args): return _twslink2pt.TWSLink2Wrap_GET_TICK(self, *args)
    def WAIT_FOR_TICK(self, *args): return _twslink2pt.TWSLink2Wrap_WAIT_FOR_TICK(self, *args)
    def VALIDATE_PRICE(self, *args): return _twslink2pt.TWSLink2Wrap_VALIDATE_PRICE(self, *args)
    def PIPS(self, *args): return _twslink2pt.TWSLink2Wrap_PIPS(self, *args)
    def EXTRACT_ARRAY_VALUE(self, *args): return _twslink2pt.TWSLink2Wrap_EXTRACT_ARRAY_VALUE(self, *args)
    def REQ_ACC_UPDATE(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_ACC_UPDATE(self, *args)
    def REQ_OPEN_ORDERS(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_OPEN_ORDERS(self, *args)
    def WAITDLL(self, *args): return _twslink2pt.TWSLink2Wrap_WAITDLL(self, *args)
    def WAIT_FOR_EVENT(self, *args): return _twslink2pt.TWSLink2Wrap_WAIT_FOR_EVENT(self, *args)
    def GET_EVENT_VAL(self, *args): return _twslink2pt.TWSLink2Wrap_GET_EVENT_VAL(self, *args)
    def GET_EVENT_VAL_I(self, *args): return _twslink2pt.TWSLink2Wrap_GET_EVENT_VAL_I(self, *args)
    def GET_EVENT_VAL_D(self, *args): return _twslink2pt.TWSLink2Wrap_GET_EVENT_VAL_D(self, *args)
    def START_APPLICATION(self, *args): return _twslink2pt.TWSLink2Wrap_START_APPLICATION(self, *args)
    def GET_CONTRACT_STATUS(self, *args): return _twslink2pt.TWSLink2Wrap_GET_CONTRACT_STATUS(self, *args)
    def PLACE_ORDER(self, *args): return _twslink2pt.TWSLink2Wrap_PLACE_ORDER(self, *args)
    def TOGGLE_ORDER(self, *args): return _twslink2pt.TWSLink2Wrap_TOGGLE_ORDER(self, *args)
    def TOGGLE_ORDER_PCT(self, *args): return _twslink2pt.TWSLink2Wrap_TOGGLE_ORDER_PCT(self, *args)
    def SET_ORDER_VAL(self, *args): return _twslink2pt.TWSLink2Wrap_SET_ORDER_VAL(self, *args)
    def GET_ORDER_VAL(self, *args): return _twslink2pt.TWSLink2Wrap_GET_ORDER_VAL(self, *args)
    def TRANSMIT(self, *args): return _twslink2pt.TWSLink2Wrap_TRANSMIT(self, *args)
    def GET_ORDERUID_LIST(self, *args): return _twslink2pt.TWSLink2Wrap_GET_ORDERUID_LIST(self, *args)
    def GET_OPEN_ORDERUID_LIST(self, *args): return _twslink2pt.TWSLink2Wrap_GET_OPEN_ORDERUID_LIST(self, *args)
    def GET_EXECUTION_PRICE(self, *args): return _twslink2pt.TWSLink2Wrap_GET_EXECUTION_PRICE(self, *args)
    def CONVERT_ID(self, *args): return _twslink2pt.TWSLink2Wrap_CONVERT_ID(self, *args)
    def CONVERT_ID_STRING(self, *args): return _twslink2pt.TWSLink2Wrap_CONVERT_ID_STRING(self, *args)
    def SET_FA_MEMBERS(self, *args): return _twslink2pt.TWSLink2Wrap_SET_FA_MEMBERS(self, *args)
    def WAIT_FOR_ORDER_STATUS(self, *args): return _twslink2pt.TWSLink2Wrap_WAIT_FOR_ORDER_STATUS(self, *args)
    def WAIT_FOR_FILLED(self, *args): return _twslink2pt.TWSLink2Wrap_WAIT_FOR_FILLED(self, *args)
    def WAIT_FOR_SUBMITTED(self, *args): return _twslink2pt.TWSLink2Wrap_WAIT_FOR_SUBMITTED(self, *args)
    def WAIT_FOR_ORDER_STATUS_RNG(self, *args): return _twslink2pt.TWSLink2Wrap_WAIT_FOR_ORDER_STATUS_RNG(self, *args)
    def GET_ORDER_STATUS(self, *args): return _twslink2pt.TWSLink2Wrap_GET_ORDER_STATUS(self, *args)
    def GET_ORDER_ERROR(self, *args): return _twslink2pt.TWSLink2Wrap_GET_ORDER_ERROR(self, *args)
    def ORDER_MODIFIABLE(self, *args): return _twslink2pt.TWSLink2Wrap_ORDER_MODIFIABLE(self, *args)
    def GET_ACC_VAL(self, *args): return _twslink2pt.TWSLink2Wrap_GET_ACC_VAL(self, *args)
    def GET_MARKET_VAL(self, *args): return _twslink2pt.TWSLink2Wrap_GET_MARKET_VAL(self, *args)
    def GET_PORTFOLIO_VAL(self, *args): return _twslink2pt.TWSLink2Wrap_GET_PORTFOLIO_VAL(self, *args)
    def GET_CONTRACT_VAL(self, *args): return _twslink2pt.TWSLink2Wrap_GET_CONTRACT_VAL(self, *args)
    def SET_CONTRACT_VAL(self, *args): return _twslink2pt.TWSLink2Wrap_SET_CONTRACT_VAL(self, *args)
    def GET_BASECURRENCY(self, *args): return _twslink2pt.TWSLink2Wrap_GET_BASECURRENCY(self, *args)
    def GET_CASH_BALANCE(self, *args): return _twslink2pt.TWSLink2Wrap_GET_CASH_BALANCE(self, *args)
    def GET_EXCHANGE_RATE(self, *args): return _twslink2pt.TWSLink2Wrap_GET_EXCHANGE_RATE(self, *args)
    def GET_ACC_NAME(self, *args): return _twslink2pt.TWSLink2Wrap_GET_ACC_NAME(self, *args)
    def GET_POSITIONS(self, *args): return _twslink2pt.TWSLink2Wrap_GET_POSITIONS(self, *args)
    def CANCEL_ORDER(self, *args): return _twslink2pt.TWSLink2Wrap_CANCEL_ORDER(self, *args)
    def CANCEL_GLOBAL(self): return _twslink2pt.TWSLink2Wrap_CANCEL_GLOBAL(self)
    def CANCEL_SELECT(self, *args): return _twslink2pt.TWSLink2Wrap_CANCEL_SELECT(self, *args)
    def CLOSE_CONTRACT(self, *args): return _twslink2pt.TWSLink2Wrap_CLOSE_CONTRACT(self, *args)
    def CANCEL_AND_CLOSE(self, *args): return _twslink2pt.TWSLink2Wrap_CANCEL_AND_CLOSE(self, *args)
    def CLOSE_CASH_POSITION(self, *args): return _twslink2pt.TWSLink2Wrap_CLOSE_CASH_POSITION(self, *args)
    def FORCE_CONTRACT(self, *args): return _twslink2pt.TWSLink2Wrap_FORCE_CONTRACT(self, *args)
    def CONNECT_XML(self, *args): return _twslink2pt.TWSLink2Wrap_CONNECT_XML(self, *args)
    def CONNECT(self, *args): return _twslink2pt.TWSLink2Wrap_CONNECT(self, *args)
    def DISCONNECT(self): return _twslink2pt.TWSLink2Wrap_DISCONNECT(self)
    def SET_DLL_PARAM(self, *args): return _twslink2pt.TWSLink2Wrap_SET_DLL_PARAM(self, *args)
    def DISPOSE(self, *args): return _twslink2pt.TWSLink2Wrap_DISPOSE(self, *args)
    def GET_DLL_PARAM(self, *args): return _twslink2pt.TWSLink2Wrap_GET_DLL_PARAM(self, *args)
    def GET_CONNECTED(self): return _twslink2pt.TWSLink2Wrap_GET_CONNECTED(self)
    def CUSTOMCOMMENT(self, *args): return _twslink2pt.TWSLink2Wrap_CUSTOMCOMMENT(self, *args)
    def CUSTOMLOG(self, *args): return _twslink2pt.TWSLink2Wrap_CUSTOMLOG(self, *args)
    def DELETE_CUSTOMLOG(self, *args): return _twslink2pt.TWSLink2Wrap_DELETE_CUSTOMLOG(self, *args)
    def SEND_MAIL(self, *args): return _twslink2pt.TWSLink2Wrap_SEND_MAIL(self, *args)
    def CREATE_MAIL_CFG(self, *args): return _twslink2pt.TWSLink2Wrap_CREATE_MAIL_CFG(self, *args)
    def SEND_MAIL_CFG(self, *args): return _twslink2pt.TWSLink2Wrap_SEND_MAIL_CFG(self, *args)
    def CREATE_FTP_CFG(self, *args): return _twslink2pt.TWSLink2Wrap_CREATE_FTP_CFG(self, *args)
    def FTP_UPLOAD(self, *args): return _twslink2pt.TWSLink2Wrap_FTP_UPLOAD(self, *args)
    def FTP_DOWNLOAD(self, *args): return _twslink2pt.TWSLink2Wrap_FTP_DOWNLOAD(self, *args)
    def TO_FILE(self, *args): return _twslink2pt.TWSLink2Wrap_TO_FILE(self, *args)
    def FROM_FILE(self, *args): return _twslink2pt.TWSLink2Wrap_FROM_FILE(self, *args)
    def GET_INT_VAR(self, *args): return _twslink2pt.TWSLink2Wrap_GET_INT_VAR(self, *args)
    def GET_DBL_VAR(self, *args): return _twslink2pt.TWSLink2Wrap_GET_DBL_VAR(self, *args)
    def GET_STR_VAR(self, *args): return _twslink2pt.TWSLink2Wrap_GET_STR_VAR(self, *args)
    def SET_INT_VAR(self, *args): return _twslink2pt.TWSLink2Wrap_SET_INT_VAR(self, *args)
    def SET_DBL_VAR(self, *args): return _twslink2pt.TWSLink2Wrap_SET_DBL_VAR(self, *args)
    def SET_STR_VAR(self, *args): return _twslink2pt.TWSLink2Wrap_SET_STR_VAR(self, *args)
    def REM_INT_VAR(self, *args): return _twslink2pt.TWSLink2Wrap_REM_INT_VAR(self, *args)
    def REM_DBL_VAR(self, *args): return _twslink2pt.TWSLink2Wrap_REM_DBL_VAR(self, *args)
    def REM_STR_VAR(self, *args): return _twslink2pt.TWSLink2Wrap_REM_STR_VAR(self, *args)
    def GET_INT(self, *args): return _twslink2pt.TWSLink2Wrap_GET_INT(self, *args)
    def GET_DBL(self, *args): return _twslink2pt.TWSLink2Wrap_GET_DBL(self, *args)
    def GET_STR(self, *args): return _twslink2pt.TWSLink2Wrap_GET_STR(self, *args)
    def ADD_INT(self, *args): return _twslink2pt.TWSLink2Wrap_ADD_INT(self, *args)
    def ADD_DBL(self, *args): return _twslink2pt.TWSLink2Wrap_ADD_DBL(self, *args)
    def NEWS_BULLETIN(self, *args): return _twslink2pt.TWSLink2Wrap_NEWS_BULLETIN(self, *args)
    def REQ_HIST_DATA(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_HIST_DATA(self, *args)
    def REQ_CURRENT_TIME(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_CURRENT_TIME(self, *args)
    def REQ_SCANNER_PARAMETER(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_SCANNER_PARAMETER(self, *args)
    def REQ_SCANNER_SUBSCRIPTION(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_SCANNER_SUBSCRIPTION(self, *args)
    def CANCEL_SCANNER_SUBSCRIPTION(self, *args): return _twslink2pt.TWSLink2Wrap_CANCEL_SCANNER_SUBSCRIPTION(self, *args)
    def DISCONNECT_DB(self, *args): return _twslink2pt.TWSLink2Wrap_DISCONNECT_DB(self, *args)
    def CONNECT_DB(self, *args): return _twslink2pt.TWSLink2Wrap_CONNECT_DB(self, *args)
    def SQL(self, *args): return _twslink2pt.TWSLink2Wrap_SQL(self, *args)
    def SQL2(self, *args): return _twslink2pt.TWSLink2Wrap_SQL2(self, *args)
    def SET_EVENT_HANDLER(self, *args): return _twslink2pt.TWSLink2Wrap_SET_EVENT_HANDLER(self, *args)
    def SET_EVENT_HANDLER_OLE(self, *args): return _twslink2pt.TWSLink2Wrap_SET_EVENT_HANDLER_OLE(self, *args)
    def REM_EVENT_HANDLER(self, *args): return _twslink2pt.TWSLink2Wrap_REM_EVENT_HANDLER(self, *args)
    def TIME_STRING(self, *args): return _twslink2pt.TWSLink2Wrap_TIME_STRING(self, *args)
    def TIME_COMPONENT(self, *args): return _twslink2pt.TWSLink2Wrap_TIME_COMPONENT(self, *args)
    def SECONDS_1970(self): return _twslink2pt.TWSLink2Wrap_SECONDS_1970(self)
    def MILLISECONDS_1970(self): return _twslink2pt.TWSLink2Wrap_MILLISECONDS_1970(self)
    def SET_TIMER(self, *args): return _twslink2pt.TWSLink2Wrap_SET_TIMER(self, *args)
    def KILL_TIMER(self, *args): return _twslink2pt.TWSLink2Wrap_KILL_TIMER(self, *args)
    def PLAY_SOUND(self, *args): return _twslink2pt.TWSLink2Wrap_PLAY_SOUND(self, *args)
    def REQ_FUNDAMENTAL_DATA(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_FUNDAMENTAL_DATA(self, *args)
    def REQ_EXECUTION_DATA(self, *args): return _twslink2pt.TWSLink2Wrap_REQ_EXECUTION_DATA(self, *args)
    def PARSE_XML(self, *args): return _twslink2pt.TWSLink2Wrap_PARSE_XML(self, *args)
    def GET_EXECUTION_DATA(self, *args): return _twslink2pt.TWSLink2Wrap_GET_EXECUTION_DATA(self, *args)
    def GET_EXECUTION_DATA_SQL(self, *args): return _twslink2pt.TWSLink2Wrap_GET_EXECUTION_DATA_SQL(self, *args)
    def GET_EXECUTION_DATA_SQL2(self, *args): return _twslink2pt.TWSLink2Wrap_GET_EXECUTION_DATA_SQL2(self, *args)
    def QUERY_DATABASE(self, *args): return _twslink2pt.TWSLink2Wrap_QUERY_DATABASE(self, *args)
    def QUERY_DATABASE_CB(self, *args): return _twslink2pt.TWSLink2Wrap_QUERY_DATABASE_CB(self, *args)
    def INIT_TWSLINK(self, *args): return _twslink2pt.TWSLink2Wrap_INIT_TWSLINK(self, *args)
    def LOGGER(self, *args): return _twslink2pt.TWSLink2Wrap_LOGGER(self, *args)
    def LOGGER2(self, *args): return _twslink2pt.TWSLink2Wrap_LOGGER2(self, *args)
    def U2A(self, *args): return _twslink2pt.TWSLink2Wrap_U2A(self, *args)
    def A2U(self, *args): return _twslink2pt.TWSLink2Wrap_A2U(self, *args)
    def RISK_SET(self, *args): return _twslink2pt.TWSLink2Wrap_RISK_SET(self, *args)
    def RISK_ENABLE(self, *args): return _twslink2pt.TWSLink2Wrap_RISK_ENABLE(self, *args)
    def RISK_TRIGGERED(self, *args): return _twslink2pt.TWSLink2Wrap_RISK_TRIGGERED(self, *args)
    def RISK_VALUE(self, *args): return _twslink2pt.TWSLink2Wrap_RISK_VALUE(self, *args)
    def RISK_RESET(self, *args): return _twslink2pt.TWSLink2Wrap_RISK_RESET(self, *args)
    def SET_HTML_REPORT(self, *args): return _twslink2pt.TWSLink2Wrap_SET_HTML_REPORT(self, *args)
    def TEST_1(self, *args): return _twslink2pt.TWSLink2Wrap_TEST_1(self, *args)
    __swig_setmethods__["_fpREGISTER_CONTRACT"] = _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_set
    __swig_getmethods__["_fpREGISTER_CONTRACT"] = _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_get
    if _newclass:_fpREGISTER_CONTRACT = _swig_property(_twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_get, _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_set)
    __swig_setmethods__["_fpREGISTER_CONTRACT2"] = _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT2_set
    __swig_getmethods__["_fpREGISTER_CONTRACT2"] = _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT2_get
    if _newclass:_fpREGISTER_CONTRACT2 = _swig_property(_twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT2_get, _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT2_set)
    __swig_setmethods__["_fpREGISTER_CONTRACT_XML"] = _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_XML_set
    __swig_getmethods__["_fpREGISTER_CONTRACT_XML"] = _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_XML_get
    if _newclass:_fpREGISTER_CONTRACT_XML = _swig_property(_twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_XML_get, _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_XML_set)
    __swig_setmethods__["_fpREGISTER_CONTRACT_XML_STYLE"] = _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_XML_STYLE_set
    __swig_getmethods__["_fpREGISTER_CONTRACT_XML_STYLE"] = _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_XML_STYLE_get
    if _newclass:_fpREGISTER_CONTRACT_XML_STYLE = _swig_property(_twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_XML_STYLE_get, _twslink2pt.TWSLink2Wrap__fpREGISTER_CONTRACT_XML_STYLE_set)
    __swig_setmethods__["_fpGET_CONTRACTUID_LIST"] = _twslink2pt.TWSLink2Wrap__fpGET_CONTRACTUID_LIST_set
    __swig_getmethods__["_fpGET_CONTRACTUID_LIST"] = _twslink2pt.TWSLink2Wrap__fpGET_CONTRACTUID_LIST_get
    if _newclass:_fpGET_CONTRACTUID_LIST = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_CONTRACTUID_LIST_get, _twslink2pt.TWSLink2Wrap__fpGET_CONTRACTUID_LIST_set)
    __swig_setmethods__["_fpWAIT_FOR_ACCEPTED"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ACCEPTED_set
    __swig_getmethods__["_fpWAIT_FOR_ACCEPTED"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ACCEPTED_get
    if _newclass:_fpWAIT_FOR_ACCEPTED = _swig_property(_twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ACCEPTED_get, _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ACCEPTED_set)
    __swig_setmethods__["_fpADD_COMBO_LEG"] = _twslink2pt.TWSLink2Wrap__fpADD_COMBO_LEG_set
    __swig_getmethods__["_fpADD_COMBO_LEG"] = _twslink2pt.TWSLink2Wrap__fpADD_COMBO_LEG_get
    if _newclass:_fpADD_COMBO_LEG = _swig_property(_twslink2pt.TWSLink2Wrap__fpADD_COMBO_LEG_get, _twslink2pt.TWSLink2Wrap__fpADD_COMBO_LEG_set)
    __swig_setmethods__["_fpREM_COMBO_LEG"] = _twslink2pt.TWSLink2Wrap__fpREM_COMBO_LEG_set
    __swig_getmethods__["_fpREM_COMBO_LEG"] = _twslink2pt.TWSLink2Wrap__fpREM_COMBO_LEG_get
    if _newclass:_fpREM_COMBO_LEG = _swig_property(_twslink2pt.TWSLink2Wrap__fpREM_COMBO_LEG_get, _twslink2pt.TWSLink2Wrap__fpREM_COMBO_LEG_set)
    __swig_setmethods__["_fpREQ_MARKET_DATA"] = _twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DATA_set
    __swig_getmethods__["_fpREQ_MARKET_DATA"] = _twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DATA_get
    if _newclass:_fpREQ_MARKET_DATA = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DATA_get, _twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DATA_set)
    __swig_setmethods__["_fpREQ_MARKET_DATA_TYPE"] = _twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DATA_TYPE_set
    __swig_getmethods__["_fpREQ_MARKET_DATA_TYPE"] = _twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DATA_TYPE_get
    if _newclass:_fpREQ_MARKET_DATA_TYPE = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DATA_TYPE_get, _twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DATA_TYPE_set)
    __swig_setmethods__["_fpREQ_MARKET_DEPTH"] = _twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DEPTH_set
    __swig_getmethods__["_fpREQ_MARKET_DEPTH"] = _twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DEPTH_get
    if _newclass:_fpREQ_MARKET_DEPTH = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DEPTH_get, _twslink2pt.TWSLink2Wrap__fpREQ_MARKET_DEPTH_set)
    __swig_setmethods__["_fpREQ_BAR_DATA"] = _twslink2pt.TWSLink2Wrap__fpREQ_BAR_DATA_set
    __swig_getmethods__["_fpREQ_BAR_DATA"] = _twslink2pt.TWSLink2Wrap__fpREQ_BAR_DATA_get
    if _newclass:_fpREQ_BAR_DATA = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_BAR_DATA_get, _twslink2pt.TWSLink2Wrap__fpREQ_BAR_DATA_set)
    __swig_setmethods__["_fpCANCEL_BAR_DATA"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_BAR_DATA_set
    __swig_getmethods__["_fpCANCEL_BAR_DATA"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_BAR_DATA_get
    if _newclass:_fpCANCEL_BAR_DATA = _swig_property(_twslink2pt.TWSLink2Wrap__fpCANCEL_BAR_DATA_get, _twslink2pt.TWSLink2Wrap__fpCANCEL_BAR_DATA_set)
    __swig_setmethods__["_fpGET_MARKET_DATA"] = _twslink2pt.TWSLink2Wrap__fpGET_MARKET_DATA_set
    __swig_getmethods__["_fpGET_MARKET_DATA"] = _twslink2pt.TWSLink2Wrap__fpGET_MARKET_DATA_get
    if _newclass:_fpGET_MARKET_DATA = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_MARKET_DATA_get, _twslink2pt.TWSLink2Wrap__fpGET_MARKET_DATA_set)
    __swig_setmethods__["_fpGET_BAR_DATA"] = _twslink2pt.TWSLink2Wrap__fpGET_BAR_DATA_set
    __swig_getmethods__["_fpGET_BAR_DATA"] = _twslink2pt.TWSLink2Wrap__fpGET_BAR_DATA_get
    if _newclass:_fpGET_BAR_DATA = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_BAR_DATA_get, _twslink2pt.TWSLink2Wrap__fpGET_BAR_DATA_set)
    __swig_setmethods__["_fpGET_MARKET_DEPTH"] = _twslink2pt.TWSLink2Wrap__fpGET_MARKET_DEPTH_set
    __swig_getmethods__["_fpGET_MARKET_DEPTH"] = _twslink2pt.TWSLink2Wrap__fpGET_MARKET_DEPTH_get
    if _newclass:_fpGET_MARKET_DEPTH = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_MARKET_DEPTH_get, _twslink2pt.TWSLink2Wrap__fpGET_MARKET_DEPTH_set)
    __swig_setmethods__["_fpGET_MARKET_DEPTH2"] = _twslink2pt.TWSLink2Wrap__fpGET_MARKET_DEPTH2_set
    __swig_getmethods__["_fpGET_MARKET_DEPTH2"] = _twslink2pt.TWSLink2Wrap__fpGET_MARKET_DEPTH2_get
    if _newclass:_fpGET_MARKET_DEPTH2 = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_MARKET_DEPTH2_get, _twslink2pt.TWSLink2Wrap__fpGET_MARKET_DEPTH2_set)
    __swig_setmethods__["_fpGET_TICK"] = _twslink2pt.TWSLink2Wrap__fpGET_TICK_set
    __swig_getmethods__["_fpGET_TICK"] = _twslink2pt.TWSLink2Wrap__fpGET_TICK_get
    if _newclass:_fpGET_TICK = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_TICK_get, _twslink2pt.TWSLink2Wrap__fpGET_TICK_set)
    __swig_setmethods__["_fpWAIT_FOR_TICK"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_TICK_set
    __swig_getmethods__["_fpWAIT_FOR_TICK"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_TICK_get
    if _newclass:_fpWAIT_FOR_TICK = _swig_property(_twslink2pt.TWSLink2Wrap__fpWAIT_FOR_TICK_get, _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_TICK_set)
    __swig_setmethods__["_fpVALIDATE_PRICE"] = _twslink2pt.TWSLink2Wrap__fpVALIDATE_PRICE_set
    __swig_getmethods__["_fpVALIDATE_PRICE"] = _twslink2pt.TWSLink2Wrap__fpVALIDATE_PRICE_get
    if _newclass:_fpVALIDATE_PRICE = _swig_property(_twslink2pt.TWSLink2Wrap__fpVALIDATE_PRICE_get, _twslink2pt.TWSLink2Wrap__fpVALIDATE_PRICE_set)
    __swig_setmethods__["_fpPIPS"] = _twslink2pt.TWSLink2Wrap__fpPIPS_set
    __swig_getmethods__["_fpPIPS"] = _twslink2pt.TWSLink2Wrap__fpPIPS_get
    if _newclass:_fpPIPS = _swig_property(_twslink2pt.TWSLink2Wrap__fpPIPS_get, _twslink2pt.TWSLink2Wrap__fpPIPS_set)
    __swig_setmethods__["_fpEXTRACT_ARRAY_VALUE"] = _twslink2pt.TWSLink2Wrap__fpEXTRACT_ARRAY_VALUE_set
    __swig_getmethods__["_fpEXTRACT_ARRAY_VALUE"] = _twslink2pt.TWSLink2Wrap__fpEXTRACT_ARRAY_VALUE_get
    if _newclass:_fpEXTRACT_ARRAY_VALUE = _swig_property(_twslink2pt.TWSLink2Wrap__fpEXTRACT_ARRAY_VALUE_get, _twslink2pt.TWSLink2Wrap__fpEXTRACT_ARRAY_VALUE_set)
    __swig_setmethods__["_fpREQ_ACC_UPDATE"] = _twslink2pt.TWSLink2Wrap__fpREQ_ACC_UPDATE_set
    __swig_getmethods__["_fpREQ_ACC_UPDATE"] = _twslink2pt.TWSLink2Wrap__fpREQ_ACC_UPDATE_get
    if _newclass:_fpREQ_ACC_UPDATE = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_ACC_UPDATE_get, _twslink2pt.TWSLink2Wrap__fpREQ_ACC_UPDATE_set)
    __swig_setmethods__["_fpREQ_OPEN_ORDERS"] = _twslink2pt.TWSLink2Wrap__fpREQ_OPEN_ORDERS_set
    __swig_getmethods__["_fpREQ_OPEN_ORDERS"] = _twslink2pt.TWSLink2Wrap__fpREQ_OPEN_ORDERS_get
    if _newclass:_fpREQ_OPEN_ORDERS = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_OPEN_ORDERS_get, _twslink2pt.TWSLink2Wrap__fpREQ_OPEN_ORDERS_set)
    __swig_setmethods__["_fpWAITDLL"] = _twslink2pt.TWSLink2Wrap__fpWAITDLL_set
    __swig_getmethods__["_fpWAITDLL"] = _twslink2pt.TWSLink2Wrap__fpWAITDLL_get
    if _newclass:_fpWAITDLL = _swig_property(_twslink2pt.TWSLink2Wrap__fpWAITDLL_get, _twslink2pt.TWSLink2Wrap__fpWAITDLL_set)
    __swig_setmethods__["_fpWAIT_FOR_EVENT"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_EVENT_set
    __swig_getmethods__["_fpWAIT_FOR_EVENT"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_EVENT_get
    if _newclass:_fpWAIT_FOR_EVENT = _swig_property(_twslink2pt.TWSLink2Wrap__fpWAIT_FOR_EVENT_get, _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_EVENT_set)
    __swig_setmethods__["_fpGET_EVENT_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_set
    __swig_getmethods__["_fpGET_EVENT_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_get
    if _newclass:_fpGET_EVENT_VAL = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_get, _twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_set)
    __swig_setmethods__["_fpGET_EVENT_VAL_I"] = _twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_I_set
    __swig_getmethods__["_fpGET_EVENT_VAL_I"] = _twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_I_get
    if _newclass:_fpGET_EVENT_VAL_I = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_I_get, _twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_I_set)
    __swig_setmethods__["_fpGET_EVENT_VAL_D"] = _twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_D_set
    __swig_getmethods__["_fpGET_EVENT_VAL_D"] = _twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_D_get
    if _newclass:_fpGET_EVENT_VAL_D = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_D_get, _twslink2pt.TWSLink2Wrap__fpGET_EVENT_VAL_D_set)
    __swig_setmethods__["_fpSTART_APPLICATION"] = _twslink2pt.TWSLink2Wrap__fpSTART_APPLICATION_set
    __swig_getmethods__["_fpSTART_APPLICATION"] = _twslink2pt.TWSLink2Wrap__fpSTART_APPLICATION_get
    if _newclass:_fpSTART_APPLICATION = _swig_property(_twslink2pt.TWSLink2Wrap__fpSTART_APPLICATION_get, _twslink2pt.TWSLink2Wrap__fpSTART_APPLICATION_set)
    __swig_setmethods__["_fpGET_CONTRACT_STATUS"] = _twslink2pt.TWSLink2Wrap__fpGET_CONTRACT_STATUS_set
    __swig_getmethods__["_fpGET_CONTRACT_STATUS"] = _twslink2pt.TWSLink2Wrap__fpGET_CONTRACT_STATUS_get
    if _newclass:_fpGET_CONTRACT_STATUS = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_CONTRACT_STATUS_get, _twslink2pt.TWSLink2Wrap__fpGET_CONTRACT_STATUS_set)
    __swig_setmethods__["_fpPLACE_ORDER"] = _twslink2pt.TWSLink2Wrap__fpPLACE_ORDER_set
    __swig_getmethods__["_fpPLACE_ORDER"] = _twslink2pt.TWSLink2Wrap__fpPLACE_ORDER_get
    if _newclass:_fpPLACE_ORDER = _swig_property(_twslink2pt.TWSLink2Wrap__fpPLACE_ORDER_get, _twslink2pt.TWSLink2Wrap__fpPLACE_ORDER_set)
    __swig_setmethods__["_fpTOGGLE_ORDER"] = _twslink2pt.TWSLink2Wrap__fpTOGGLE_ORDER_set
    __swig_getmethods__["_fpTOGGLE_ORDER"] = _twslink2pt.TWSLink2Wrap__fpTOGGLE_ORDER_get
    if _newclass:_fpTOGGLE_ORDER = _swig_property(_twslink2pt.TWSLink2Wrap__fpTOGGLE_ORDER_get, _twslink2pt.TWSLink2Wrap__fpTOGGLE_ORDER_set)
    __swig_setmethods__["_fpTOGGLE_ORDER_PCT"] = _twslink2pt.TWSLink2Wrap__fpTOGGLE_ORDER_PCT_set
    __swig_getmethods__["_fpTOGGLE_ORDER_PCT"] = _twslink2pt.TWSLink2Wrap__fpTOGGLE_ORDER_PCT_get
    if _newclass:_fpTOGGLE_ORDER_PCT = _swig_property(_twslink2pt.TWSLink2Wrap__fpTOGGLE_ORDER_PCT_get, _twslink2pt.TWSLink2Wrap__fpTOGGLE_ORDER_PCT_set)
    __swig_setmethods__["_fpSET_ORDER_VAL"] = _twslink2pt.TWSLink2Wrap__fpSET_ORDER_VAL_set
    __swig_getmethods__["_fpSET_ORDER_VAL"] = _twslink2pt.TWSLink2Wrap__fpSET_ORDER_VAL_get
    if _newclass:_fpSET_ORDER_VAL = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_ORDER_VAL_get, _twslink2pt.TWSLink2Wrap__fpSET_ORDER_VAL_set)
    __swig_setmethods__["_fpGET_ORDER_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_ORDER_VAL_set
    __swig_getmethods__["_fpGET_ORDER_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_ORDER_VAL_get
    if _newclass:_fpGET_ORDER_VAL = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_ORDER_VAL_get, _twslink2pt.TWSLink2Wrap__fpGET_ORDER_VAL_set)
    __swig_setmethods__["_fpTRANSMIT"] = _twslink2pt.TWSLink2Wrap__fpTRANSMIT_set
    __swig_getmethods__["_fpTRANSMIT"] = _twslink2pt.TWSLink2Wrap__fpTRANSMIT_get
    if _newclass:_fpTRANSMIT = _swig_property(_twslink2pt.TWSLink2Wrap__fpTRANSMIT_get, _twslink2pt.TWSLink2Wrap__fpTRANSMIT_set)
    __swig_setmethods__["_fpGET_ORDERUID_LIST"] = _twslink2pt.TWSLink2Wrap__fpGET_ORDERUID_LIST_set
    __swig_getmethods__["_fpGET_ORDERUID_LIST"] = _twslink2pt.TWSLink2Wrap__fpGET_ORDERUID_LIST_get
    if _newclass:_fpGET_ORDERUID_LIST = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_ORDERUID_LIST_get, _twslink2pt.TWSLink2Wrap__fpGET_ORDERUID_LIST_set)
    __swig_setmethods__["_fpGET_OPEN_ORDERUID_LIST"] = _twslink2pt.TWSLink2Wrap__fpGET_OPEN_ORDERUID_LIST_set
    __swig_getmethods__["_fpGET_OPEN_ORDERUID_LIST"] = _twslink2pt.TWSLink2Wrap__fpGET_OPEN_ORDERUID_LIST_get
    if _newclass:_fpGET_OPEN_ORDERUID_LIST = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_OPEN_ORDERUID_LIST_get, _twslink2pt.TWSLink2Wrap__fpGET_OPEN_ORDERUID_LIST_set)
    __swig_setmethods__["_fpGET_EXECUTION_PRICE"] = _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_PRICE_set
    __swig_getmethods__["_fpGET_EXECUTION_PRICE"] = _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_PRICE_get
    if _newclass:_fpGET_EXECUTION_PRICE = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_PRICE_get, _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_PRICE_set)
    __swig_setmethods__["_fpCONVERT_ID"] = _twslink2pt.TWSLink2Wrap__fpCONVERT_ID_set
    __swig_getmethods__["_fpCONVERT_ID"] = _twslink2pt.TWSLink2Wrap__fpCONVERT_ID_get
    if _newclass:_fpCONVERT_ID = _swig_property(_twslink2pt.TWSLink2Wrap__fpCONVERT_ID_get, _twslink2pt.TWSLink2Wrap__fpCONVERT_ID_set)
    __swig_setmethods__["_fpCONVERT_ID_STRING"] = _twslink2pt.TWSLink2Wrap__fpCONVERT_ID_STRING_set
    __swig_getmethods__["_fpCONVERT_ID_STRING"] = _twslink2pt.TWSLink2Wrap__fpCONVERT_ID_STRING_get
    if _newclass:_fpCONVERT_ID_STRING = _swig_property(_twslink2pt.TWSLink2Wrap__fpCONVERT_ID_STRING_get, _twslink2pt.TWSLink2Wrap__fpCONVERT_ID_STRING_set)
    __swig_setmethods__["_fpSET_FA_MEMBERS"] = _twslink2pt.TWSLink2Wrap__fpSET_FA_MEMBERS_set
    __swig_getmethods__["_fpSET_FA_MEMBERS"] = _twslink2pt.TWSLink2Wrap__fpSET_FA_MEMBERS_get
    if _newclass:_fpSET_FA_MEMBERS = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_FA_MEMBERS_get, _twslink2pt.TWSLink2Wrap__fpSET_FA_MEMBERS_set)
    __swig_setmethods__["_fpWAIT_FOR_ORDER_STATUS"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ORDER_STATUS_set
    __swig_getmethods__["_fpWAIT_FOR_ORDER_STATUS"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ORDER_STATUS_get
    if _newclass:_fpWAIT_FOR_ORDER_STATUS = _swig_property(_twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ORDER_STATUS_get, _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ORDER_STATUS_set)
    __swig_setmethods__["_fpWAIT_FOR_FILLED"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_FILLED_set
    __swig_getmethods__["_fpWAIT_FOR_FILLED"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_FILLED_get
    if _newclass:_fpWAIT_FOR_FILLED = _swig_property(_twslink2pt.TWSLink2Wrap__fpWAIT_FOR_FILLED_get, _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_FILLED_set)
    __swig_setmethods__["_fpWAIT_FOR_SUBMITTED"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_SUBMITTED_set
    __swig_getmethods__["_fpWAIT_FOR_SUBMITTED"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_SUBMITTED_get
    if _newclass:_fpWAIT_FOR_SUBMITTED = _swig_property(_twslink2pt.TWSLink2Wrap__fpWAIT_FOR_SUBMITTED_get, _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_SUBMITTED_set)
    __swig_setmethods__["_fpWAIT_FOR_ORDER_STATUS_RNG"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ORDER_STATUS_RNG_set
    __swig_getmethods__["_fpWAIT_FOR_ORDER_STATUS_RNG"] = _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ORDER_STATUS_RNG_get
    if _newclass:_fpWAIT_FOR_ORDER_STATUS_RNG = _swig_property(_twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ORDER_STATUS_RNG_get, _twslink2pt.TWSLink2Wrap__fpWAIT_FOR_ORDER_STATUS_RNG_set)
    __swig_setmethods__["_fpGET_ORDER_STATUS"] = _twslink2pt.TWSLink2Wrap__fpGET_ORDER_STATUS_set
    __swig_getmethods__["_fpGET_ORDER_STATUS"] = _twslink2pt.TWSLink2Wrap__fpGET_ORDER_STATUS_get
    if _newclass:_fpGET_ORDER_STATUS = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_ORDER_STATUS_get, _twslink2pt.TWSLink2Wrap__fpGET_ORDER_STATUS_set)
    __swig_setmethods__["_fpGET_ORDER_ERROR"] = _twslink2pt.TWSLink2Wrap__fpGET_ORDER_ERROR_set
    __swig_getmethods__["_fpGET_ORDER_ERROR"] = _twslink2pt.TWSLink2Wrap__fpGET_ORDER_ERROR_get
    if _newclass:_fpGET_ORDER_ERROR = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_ORDER_ERROR_get, _twslink2pt.TWSLink2Wrap__fpGET_ORDER_ERROR_set)
    __swig_setmethods__["_fpORDER_MODIFIABLE"] = _twslink2pt.TWSLink2Wrap__fpORDER_MODIFIABLE_set
    __swig_getmethods__["_fpORDER_MODIFIABLE"] = _twslink2pt.TWSLink2Wrap__fpORDER_MODIFIABLE_get
    if _newclass:_fpORDER_MODIFIABLE = _swig_property(_twslink2pt.TWSLink2Wrap__fpORDER_MODIFIABLE_get, _twslink2pt.TWSLink2Wrap__fpORDER_MODIFIABLE_set)
    __swig_setmethods__["_fpGET_ACC_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_ACC_VAL_set
    __swig_getmethods__["_fpGET_ACC_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_ACC_VAL_get
    if _newclass:_fpGET_ACC_VAL = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_ACC_VAL_get, _twslink2pt.TWSLink2Wrap__fpGET_ACC_VAL_set)
    __swig_setmethods__["_fpGET_MARKET_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_MARKET_VAL_set
    __swig_getmethods__["_fpGET_MARKET_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_MARKET_VAL_get
    if _newclass:_fpGET_MARKET_VAL = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_MARKET_VAL_get, _twslink2pt.TWSLink2Wrap__fpGET_MARKET_VAL_set)
    __swig_setmethods__["_fpGET_PORTFOLIO_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_PORTFOLIO_VAL_set
    __swig_getmethods__["_fpGET_PORTFOLIO_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_PORTFOLIO_VAL_get
    if _newclass:_fpGET_PORTFOLIO_VAL = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_PORTFOLIO_VAL_get, _twslink2pt.TWSLink2Wrap__fpGET_PORTFOLIO_VAL_set)
    __swig_setmethods__["_fpGET_CONTRACT_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_CONTRACT_VAL_set
    __swig_getmethods__["_fpGET_CONTRACT_VAL"] = _twslink2pt.TWSLink2Wrap__fpGET_CONTRACT_VAL_get
    if _newclass:_fpGET_CONTRACT_VAL = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_CONTRACT_VAL_get, _twslink2pt.TWSLink2Wrap__fpGET_CONTRACT_VAL_set)
    __swig_setmethods__["_fpSET_CONTRACT_VAL"] = _twslink2pt.TWSLink2Wrap__fpSET_CONTRACT_VAL_set
    __swig_getmethods__["_fpSET_CONTRACT_VAL"] = _twslink2pt.TWSLink2Wrap__fpSET_CONTRACT_VAL_get
    if _newclass:_fpSET_CONTRACT_VAL = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_CONTRACT_VAL_get, _twslink2pt.TWSLink2Wrap__fpSET_CONTRACT_VAL_set)
    __swig_setmethods__["_fpGET_BASECURRENCY"] = _twslink2pt.TWSLink2Wrap__fpGET_BASECURRENCY_set
    __swig_getmethods__["_fpGET_BASECURRENCY"] = _twslink2pt.TWSLink2Wrap__fpGET_BASECURRENCY_get
    if _newclass:_fpGET_BASECURRENCY = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_BASECURRENCY_get, _twslink2pt.TWSLink2Wrap__fpGET_BASECURRENCY_set)
    __swig_setmethods__["_fpGET_CASH_BALANCE"] = _twslink2pt.TWSLink2Wrap__fpGET_CASH_BALANCE_set
    __swig_getmethods__["_fpGET_CASH_BALANCE"] = _twslink2pt.TWSLink2Wrap__fpGET_CASH_BALANCE_get
    if _newclass:_fpGET_CASH_BALANCE = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_CASH_BALANCE_get, _twslink2pt.TWSLink2Wrap__fpGET_CASH_BALANCE_set)
    __swig_setmethods__["_fpGET_EXCHANGE_RATE"] = _twslink2pt.TWSLink2Wrap__fpGET_EXCHANGE_RATE_set
    __swig_getmethods__["_fpGET_EXCHANGE_RATE"] = _twslink2pt.TWSLink2Wrap__fpGET_EXCHANGE_RATE_get
    if _newclass:_fpGET_EXCHANGE_RATE = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_EXCHANGE_RATE_get, _twslink2pt.TWSLink2Wrap__fpGET_EXCHANGE_RATE_set)
    __swig_setmethods__["_fpGET_ACC_NAME"] = _twslink2pt.TWSLink2Wrap__fpGET_ACC_NAME_set
    __swig_getmethods__["_fpGET_ACC_NAME"] = _twslink2pt.TWSLink2Wrap__fpGET_ACC_NAME_get
    if _newclass:_fpGET_ACC_NAME = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_ACC_NAME_get, _twslink2pt.TWSLink2Wrap__fpGET_ACC_NAME_set)
    __swig_setmethods__["_fpGET_POSITIONS"] = _twslink2pt.TWSLink2Wrap__fpGET_POSITIONS_set
    __swig_getmethods__["_fpGET_POSITIONS"] = _twslink2pt.TWSLink2Wrap__fpGET_POSITIONS_get
    if _newclass:_fpGET_POSITIONS = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_POSITIONS_get, _twslink2pt.TWSLink2Wrap__fpGET_POSITIONS_set)
    __swig_setmethods__["_fpCANCEL_ORDER"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_ORDER_set
    __swig_getmethods__["_fpCANCEL_ORDER"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_ORDER_get
    if _newclass:_fpCANCEL_ORDER = _swig_property(_twslink2pt.TWSLink2Wrap__fpCANCEL_ORDER_get, _twslink2pt.TWSLink2Wrap__fpCANCEL_ORDER_set)
    __swig_setmethods__["_fpCANCEL_GLOBAL"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_GLOBAL_set
    __swig_getmethods__["_fpCANCEL_GLOBAL"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_GLOBAL_get
    if _newclass:_fpCANCEL_GLOBAL = _swig_property(_twslink2pt.TWSLink2Wrap__fpCANCEL_GLOBAL_get, _twslink2pt.TWSLink2Wrap__fpCANCEL_GLOBAL_set)
    __swig_setmethods__["_fpCANCEL_SELECT"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_SELECT_set
    __swig_getmethods__["_fpCANCEL_SELECT"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_SELECT_get
    if _newclass:_fpCANCEL_SELECT = _swig_property(_twslink2pt.TWSLink2Wrap__fpCANCEL_SELECT_get, _twslink2pt.TWSLink2Wrap__fpCANCEL_SELECT_set)
    __swig_setmethods__["_fpCLOSE_CONTRACT"] = _twslink2pt.TWSLink2Wrap__fpCLOSE_CONTRACT_set
    __swig_getmethods__["_fpCLOSE_CONTRACT"] = _twslink2pt.TWSLink2Wrap__fpCLOSE_CONTRACT_get
    if _newclass:_fpCLOSE_CONTRACT = _swig_property(_twslink2pt.TWSLink2Wrap__fpCLOSE_CONTRACT_get, _twslink2pt.TWSLink2Wrap__fpCLOSE_CONTRACT_set)
    __swig_setmethods__["_fpCANCEL_AND_CLOSE"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_AND_CLOSE_set
    __swig_getmethods__["_fpCANCEL_AND_CLOSE"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_AND_CLOSE_get
    if _newclass:_fpCANCEL_AND_CLOSE = _swig_property(_twslink2pt.TWSLink2Wrap__fpCANCEL_AND_CLOSE_get, _twslink2pt.TWSLink2Wrap__fpCANCEL_AND_CLOSE_set)
    __swig_setmethods__["_fpCLOSE_CASH_POSITION"] = _twslink2pt.TWSLink2Wrap__fpCLOSE_CASH_POSITION_set
    __swig_getmethods__["_fpCLOSE_CASH_POSITION"] = _twslink2pt.TWSLink2Wrap__fpCLOSE_CASH_POSITION_get
    if _newclass:_fpCLOSE_CASH_POSITION = _swig_property(_twslink2pt.TWSLink2Wrap__fpCLOSE_CASH_POSITION_get, _twslink2pt.TWSLink2Wrap__fpCLOSE_CASH_POSITION_set)
    __swig_setmethods__["_fpFORCE_CONTRACT"] = _twslink2pt.TWSLink2Wrap__fpFORCE_CONTRACT_set
    __swig_getmethods__["_fpFORCE_CONTRACT"] = _twslink2pt.TWSLink2Wrap__fpFORCE_CONTRACT_get
    if _newclass:_fpFORCE_CONTRACT = _swig_property(_twslink2pt.TWSLink2Wrap__fpFORCE_CONTRACT_get, _twslink2pt.TWSLink2Wrap__fpFORCE_CONTRACT_set)
    __swig_setmethods__["_fpCONNECT_XML"] = _twslink2pt.TWSLink2Wrap__fpCONNECT_XML_set
    __swig_getmethods__["_fpCONNECT_XML"] = _twslink2pt.TWSLink2Wrap__fpCONNECT_XML_get
    if _newclass:_fpCONNECT_XML = _swig_property(_twslink2pt.TWSLink2Wrap__fpCONNECT_XML_get, _twslink2pt.TWSLink2Wrap__fpCONNECT_XML_set)
    __swig_setmethods__["_fpCONNECT"] = _twslink2pt.TWSLink2Wrap__fpCONNECT_set
    __swig_getmethods__["_fpCONNECT"] = _twslink2pt.TWSLink2Wrap__fpCONNECT_get
    if _newclass:_fpCONNECT = _swig_property(_twslink2pt.TWSLink2Wrap__fpCONNECT_get, _twslink2pt.TWSLink2Wrap__fpCONNECT_set)
    __swig_setmethods__["_fpDISCONNECT"] = _twslink2pt.TWSLink2Wrap__fpDISCONNECT_set
    __swig_getmethods__["_fpDISCONNECT"] = _twslink2pt.TWSLink2Wrap__fpDISCONNECT_get
    if _newclass:_fpDISCONNECT = _swig_property(_twslink2pt.TWSLink2Wrap__fpDISCONNECT_get, _twslink2pt.TWSLink2Wrap__fpDISCONNECT_set)
    __swig_setmethods__["_fpSET_DLL_PARAM"] = _twslink2pt.TWSLink2Wrap__fpSET_DLL_PARAM_set
    __swig_getmethods__["_fpSET_DLL_PARAM"] = _twslink2pt.TWSLink2Wrap__fpSET_DLL_PARAM_get
    if _newclass:_fpSET_DLL_PARAM = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_DLL_PARAM_get, _twslink2pt.TWSLink2Wrap__fpSET_DLL_PARAM_set)
    __swig_setmethods__["_fpDISPOSE"] = _twslink2pt.TWSLink2Wrap__fpDISPOSE_set
    __swig_getmethods__["_fpDISPOSE"] = _twslink2pt.TWSLink2Wrap__fpDISPOSE_get
    if _newclass:_fpDISPOSE = _swig_property(_twslink2pt.TWSLink2Wrap__fpDISPOSE_get, _twslink2pt.TWSLink2Wrap__fpDISPOSE_set)
    __swig_setmethods__["_fpGET_DLL_PARAM"] = _twslink2pt.TWSLink2Wrap__fpGET_DLL_PARAM_set
    __swig_getmethods__["_fpGET_DLL_PARAM"] = _twslink2pt.TWSLink2Wrap__fpGET_DLL_PARAM_get
    if _newclass:_fpGET_DLL_PARAM = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_DLL_PARAM_get, _twslink2pt.TWSLink2Wrap__fpGET_DLL_PARAM_set)
    __swig_setmethods__["_fpGET_CONNECTED"] = _twslink2pt.TWSLink2Wrap__fpGET_CONNECTED_set
    __swig_getmethods__["_fpGET_CONNECTED"] = _twslink2pt.TWSLink2Wrap__fpGET_CONNECTED_get
    if _newclass:_fpGET_CONNECTED = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_CONNECTED_get, _twslink2pt.TWSLink2Wrap__fpGET_CONNECTED_set)
    __swig_setmethods__["_fpCUSTOMCOMMENT"] = _twslink2pt.TWSLink2Wrap__fpCUSTOMCOMMENT_set
    __swig_getmethods__["_fpCUSTOMCOMMENT"] = _twslink2pt.TWSLink2Wrap__fpCUSTOMCOMMENT_get
    if _newclass:_fpCUSTOMCOMMENT = _swig_property(_twslink2pt.TWSLink2Wrap__fpCUSTOMCOMMENT_get, _twslink2pt.TWSLink2Wrap__fpCUSTOMCOMMENT_set)
    __swig_setmethods__["_fpCUSTOMLOG"] = _twslink2pt.TWSLink2Wrap__fpCUSTOMLOG_set
    __swig_getmethods__["_fpCUSTOMLOG"] = _twslink2pt.TWSLink2Wrap__fpCUSTOMLOG_get
    if _newclass:_fpCUSTOMLOG = _swig_property(_twslink2pt.TWSLink2Wrap__fpCUSTOMLOG_get, _twslink2pt.TWSLink2Wrap__fpCUSTOMLOG_set)
    __swig_setmethods__["_fpDELETE_CUSTOMLOG"] = _twslink2pt.TWSLink2Wrap__fpDELETE_CUSTOMLOG_set
    __swig_getmethods__["_fpDELETE_CUSTOMLOG"] = _twslink2pt.TWSLink2Wrap__fpDELETE_CUSTOMLOG_get
    if _newclass:_fpDELETE_CUSTOMLOG = _swig_property(_twslink2pt.TWSLink2Wrap__fpDELETE_CUSTOMLOG_get, _twslink2pt.TWSLink2Wrap__fpDELETE_CUSTOMLOG_set)
    __swig_setmethods__["_fpSEND_MAIL"] = _twslink2pt.TWSLink2Wrap__fpSEND_MAIL_set
    __swig_getmethods__["_fpSEND_MAIL"] = _twslink2pt.TWSLink2Wrap__fpSEND_MAIL_get
    if _newclass:_fpSEND_MAIL = _swig_property(_twslink2pt.TWSLink2Wrap__fpSEND_MAIL_get, _twslink2pt.TWSLink2Wrap__fpSEND_MAIL_set)
    __swig_setmethods__["_fpCREATE_MAIL_CFG"] = _twslink2pt.TWSLink2Wrap__fpCREATE_MAIL_CFG_set
    __swig_getmethods__["_fpCREATE_MAIL_CFG"] = _twslink2pt.TWSLink2Wrap__fpCREATE_MAIL_CFG_get
    if _newclass:_fpCREATE_MAIL_CFG = _swig_property(_twslink2pt.TWSLink2Wrap__fpCREATE_MAIL_CFG_get, _twslink2pt.TWSLink2Wrap__fpCREATE_MAIL_CFG_set)
    __swig_setmethods__["_fpSEND_MAIL_CFG"] = _twslink2pt.TWSLink2Wrap__fpSEND_MAIL_CFG_set
    __swig_getmethods__["_fpSEND_MAIL_CFG"] = _twslink2pt.TWSLink2Wrap__fpSEND_MAIL_CFG_get
    if _newclass:_fpSEND_MAIL_CFG = _swig_property(_twslink2pt.TWSLink2Wrap__fpSEND_MAIL_CFG_get, _twslink2pt.TWSLink2Wrap__fpSEND_MAIL_CFG_set)
    __swig_setmethods__["_fpCREATE_FTP_CFG"] = _twslink2pt.TWSLink2Wrap__fpCREATE_FTP_CFG_set
    __swig_getmethods__["_fpCREATE_FTP_CFG"] = _twslink2pt.TWSLink2Wrap__fpCREATE_FTP_CFG_get
    if _newclass:_fpCREATE_FTP_CFG = _swig_property(_twslink2pt.TWSLink2Wrap__fpCREATE_FTP_CFG_get, _twslink2pt.TWSLink2Wrap__fpCREATE_FTP_CFG_set)
    __swig_setmethods__["_fpFTP_UPLOAD"] = _twslink2pt.TWSLink2Wrap__fpFTP_UPLOAD_set
    __swig_getmethods__["_fpFTP_UPLOAD"] = _twslink2pt.TWSLink2Wrap__fpFTP_UPLOAD_get
    if _newclass:_fpFTP_UPLOAD = _swig_property(_twslink2pt.TWSLink2Wrap__fpFTP_UPLOAD_get, _twslink2pt.TWSLink2Wrap__fpFTP_UPLOAD_set)
    __swig_setmethods__["_fpFTP_DOWNLOAD"] = _twslink2pt.TWSLink2Wrap__fpFTP_DOWNLOAD_set
    __swig_getmethods__["_fpFTP_DOWNLOAD"] = _twslink2pt.TWSLink2Wrap__fpFTP_DOWNLOAD_get
    if _newclass:_fpFTP_DOWNLOAD = _swig_property(_twslink2pt.TWSLink2Wrap__fpFTP_DOWNLOAD_get, _twslink2pt.TWSLink2Wrap__fpFTP_DOWNLOAD_set)
    __swig_setmethods__["_fpTO_FILE"] = _twslink2pt.TWSLink2Wrap__fpTO_FILE_set
    __swig_getmethods__["_fpTO_FILE"] = _twslink2pt.TWSLink2Wrap__fpTO_FILE_get
    if _newclass:_fpTO_FILE = _swig_property(_twslink2pt.TWSLink2Wrap__fpTO_FILE_get, _twslink2pt.TWSLink2Wrap__fpTO_FILE_set)
    __swig_setmethods__["_fpFROM_FILE"] = _twslink2pt.TWSLink2Wrap__fpFROM_FILE_set
    __swig_getmethods__["_fpFROM_FILE"] = _twslink2pt.TWSLink2Wrap__fpFROM_FILE_get
    if _newclass:_fpFROM_FILE = _swig_property(_twslink2pt.TWSLink2Wrap__fpFROM_FILE_get, _twslink2pt.TWSLink2Wrap__fpFROM_FILE_set)
    __swig_setmethods__["_fpGET_INT_VAR"] = _twslink2pt.TWSLink2Wrap__fpGET_INT_VAR_set
    __swig_getmethods__["_fpGET_INT_VAR"] = _twslink2pt.TWSLink2Wrap__fpGET_INT_VAR_get
    if _newclass:_fpGET_INT_VAR = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_INT_VAR_get, _twslink2pt.TWSLink2Wrap__fpGET_INT_VAR_set)
    __swig_setmethods__["_fpGET_DBL_VAR"] = _twslink2pt.TWSLink2Wrap__fpGET_DBL_VAR_set
    __swig_getmethods__["_fpGET_DBL_VAR"] = _twslink2pt.TWSLink2Wrap__fpGET_DBL_VAR_get
    if _newclass:_fpGET_DBL_VAR = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_DBL_VAR_get, _twslink2pt.TWSLink2Wrap__fpGET_DBL_VAR_set)
    __swig_setmethods__["_fpGET_STR_VAR"] = _twslink2pt.TWSLink2Wrap__fpGET_STR_VAR_set
    __swig_getmethods__["_fpGET_STR_VAR"] = _twslink2pt.TWSLink2Wrap__fpGET_STR_VAR_get
    if _newclass:_fpGET_STR_VAR = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_STR_VAR_get, _twslink2pt.TWSLink2Wrap__fpGET_STR_VAR_set)
    __swig_setmethods__["_fpSET_INT_VAR"] = _twslink2pt.TWSLink2Wrap__fpSET_INT_VAR_set
    __swig_getmethods__["_fpSET_INT_VAR"] = _twslink2pt.TWSLink2Wrap__fpSET_INT_VAR_get
    if _newclass:_fpSET_INT_VAR = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_INT_VAR_get, _twslink2pt.TWSLink2Wrap__fpSET_INT_VAR_set)
    __swig_setmethods__["_fpSET_DBL_VAR"] = _twslink2pt.TWSLink2Wrap__fpSET_DBL_VAR_set
    __swig_getmethods__["_fpSET_DBL_VAR"] = _twslink2pt.TWSLink2Wrap__fpSET_DBL_VAR_get
    if _newclass:_fpSET_DBL_VAR = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_DBL_VAR_get, _twslink2pt.TWSLink2Wrap__fpSET_DBL_VAR_set)
    __swig_setmethods__["_fpSET_STR_VAR"] = _twslink2pt.TWSLink2Wrap__fpSET_STR_VAR_set
    __swig_getmethods__["_fpSET_STR_VAR"] = _twslink2pt.TWSLink2Wrap__fpSET_STR_VAR_get
    if _newclass:_fpSET_STR_VAR = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_STR_VAR_get, _twslink2pt.TWSLink2Wrap__fpSET_STR_VAR_set)
    __swig_setmethods__["_fpREM_INT_VAR"] = _twslink2pt.TWSLink2Wrap__fpREM_INT_VAR_set
    __swig_getmethods__["_fpREM_INT_VAR"] = _twslink2pt.TWSLink2Wrap__fpREM_INT_VAR_get
    if _newclass:_fpREM_INT_VAR = _swig_property(_twslink2pt.TWSLink2Wrap__fpREM_INT_VAR_get, _twslink2pt.TWSLink2Wrap__fpREM_INT_VAR_set)
    __swig_setmethods__["_fpREM_DBL_VAR"] = _twslink2pt.TWSLink2Wrap__fpREM_DBL_VAR_set
    __swig_getmethods__["_fpREM_DBL_VAR"] = _twslink2pt.TWSLink2Wrap__fpREM_DBL_VAR_get
    if _newclass:_fpREM_DBL_VAR = _swig_property(_twslink2pt.TWSLink2Wrap__fpREM_DBL_VAR_get, _twslink2pt.TWSLink2Wrap__fpREM_DBL_VAR_set)
    __swig_setmethods__["_fpREM_STR_VAR"] = _twslink2pt.TWSLink2Wrap__fpREM_STR_VAR_set
    __swig_getmethods__["_fpREM_STR_VAR"] = _twslink2pt.TWSLink2Wrap__fpREM_STR_VAR_get
    if _newclass:_fpREM_STR_VAR = _swig_property(_twslink2pt.TWSLink2Wrap__fpREM_STR_VAR_get, _twslink2pt.TWSLink2Wrap__fpREM_STR_VAR_set)
    __swig_setmethods__["_fpGET_INT"] = _twslink2pt.TWSLink2Wrap__fpGET_INT_set
    __swig_getmethods__["_fpGET_INT"] = _twslink2pt.TWSLink2Wrap__fpGET_INT_get
    if _newclass:_fpGET_INT = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_INT_get, _twslink2pt.TWSLink2Wrap__fpGET_INT_set)
    __swig_setmethods__["_fpGET_DBL"] = _twslink2pt.TWSLink2Wrap__fpGET_DBL_set
    __swig_getmethods__["_fpGET_DBL"] = _twslink2pt.TWSLink2Wrap__fpGET_DBL_get
    if _newclass:_fpGET_DBL = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_DBL_get, _twslink2pt.TWSLink2Wrap__fpGET_DBL_set)
    __swig_setmethods__["_fpGET_STR"] = _twslink2pt.TWSLink2Wrap__fpGET_STR_set
    __swig_getmethods__["_fpGET_STR"] = _twslink2pt.TWSLink2Wrap__fpGET_STR_get
    if _newclass:_fpGET_STR = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_STR_get, _twslink2pt.TWSLink2Wrap__fpGET_STR_set)
    __swig_setmethods__["_fpADD_INT"] = _twslink2pt.TWSLink2Wrap__fpADD_INT_set
    __swig_getmethods__["_fpADD_INT"] = _twslink2pt.TWSLink2Wrap__fpADD_INT_get
    if _newclass:_fpADD_INT = _swig_property(_twslink2pt.TWSLink2Wrap__fpADD_INT_get, _twslink2pt.TWSLink2Wrap__fpADD_INT_set)
    __swig_setmethods__["_fpADD_DBL"] = _twslink2pt.TWSLink2Wrap__fpADD_DBL_set
    __swig_getmethods__["_fpADD_DBL"] = _twslink2pt.TWSLink2Wrap__fpADD_DBL_get
    if _newclass:_fpADD_DBL = _swig_property(_twslink2pt.TWSLink2Wrap__fpADD_DBL_get, _twslink2pt.TWSLink2Wrap__fpADD_DBL_set)
    __swig_setmethods__["_fpNEWS_BULLETIN"] = _twslink2pt.TWSLink2Wrap__fpNEWS_BULLETIN_set
    __swig_getmethods__["_fpNEWS_BULLETIN"] = _twslink2pt.TWSLink2Wrap__fpNEWS_BULLETIN_get
    if _newclass:_fpNEWS_BULLETIN = _swig_property(_twslink2pt.TWSLink2Wrap__fpNEWS_BULLETIN_get, _twslink2pt.TWSLink2Wrap__fpNEWS_BULLETIN_set)
    __swig_setmethods__["_fpREQ_HIST_DATA"] = _twslink2pt.TWSLink2Wrap__fpREQ_HIST_DATA_set
    __swig_getmethods__["_fpREQ_HIST_DATA"] = _twslink2pt.TWSLink2Wrap__fpREQ_HIST_DATA_get
    if _newclass:_fpREQ_HIST_DATA = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_HIST_DATA_get, _twslink2pt.TWSLink2Wrap__fpREQ_HIST_DATA_set)
    __swig_setmethods__["_fpREQ_CURRENT_TIME"] = _twslink2pt.TWSLink2Wrap__fpREQ_CURRENT_TIME_set
    __swig_getmethods__["_fpREQ_CURRENT_TIME"] = _twslink2pt.TWSLink2Wrap__fpREQ_CURRENT_TIME_get
    if _newclass:_fpREQ_CURRENT_TIME = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_CURRENT_TIME_get, _twslink2pt.TWSLink2Wrap__fpREQ_CURRENT_TIME_set)
    __swig_setmethods__["_fpREQ_SCANNER_PARAMETER"] = _twslink2pt.TWSLink2Wrap__fpREQ_SCANNER_PARAMETER_set
    __swig_getmethods__["_fpREQ_SCANNER_PARAMETER"] = _twslink2pt.TWSLink2Wrap__fpREQ_SCANNER_PARAMETER_get
    if _newclass:_fpREQ_SCANNER_PARAMETER = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_SCANNER_PARAMETER_get, _twslink2pt.TWSLink2Wrap__fpREQ_SCANNER_PARAMETER_set)
    __swig_setmethods__["_fpREQ_SCANNER_SUBSCRIPTION"] = _twslink2pt.TWSLink2Wrap__fpREQ_SCANNER_SUBSCRIPTION_set
    __swig_getmethods__["_fpREQ_SCANNER_SUBSCRIPTION"] = _twslink2pt.TWSLink2Wrap__fpREQ_SCANNER_SUBSCRIPTION_get
    if _newclass:_fpREQ_SCANNER_SUBSCRIPTION = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_SCANNER_SUBSCRIPTION_get, _twslink2pt.TWSLink2Wrap__fpREQ_SCANNER_SUBSCRIPTION_set)
    __swig_setmethods__["_fpCANCEL_SCANNER_SUBSCRIPTION"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_SCANNER_SUBSCRIPTION_set
    __swig_getmethods__["_fpCANCEL_SCANNER_SUBSCRIPTION"] = _twslink2pt.TWSLink2Wrap__fpCANCEL_SCANNER_SUBSCRIPTION_get
    if _newclass:_fpCANCEL_SCANNER_SUBSCRIPTION = _swig_property(_twslink2pt.TWSLink2Wrap__fpCANCEL_SCANNER_SUBSCRIPTION_get, _twslink2pt.TWSLink2Wrap__fpCANCEL_SCANNER_SUBSCRIPTION_set)
    __swig_setmethods__["_fpDISCONNECT_DB"] = _twslink2pt.TWSLink2Wrap__fpDISCONNECT_DB_set
    __swig_getmethods__["_fpDISCONNECT_DB"] = _twslink2pt.TWSLink2Wrap__fpDISCONNECT_DB_get
    if _newclass:_fpDISCONNECT_DB = _swig_property(_twslink2pt.TWSLink2Wrap__fpDISCONNECT_DB_get, _twslink2pt.TWSLink2Wrap__fpDISCONNECT_DB_set)
    __swig_setmethods__["_fpCONNECT_DB"] = _twslink2pt.TWSLink2Wrap__fpCONNECT_DB_set
    __swig_getmethods__["_fpCONNECT_DB"] = _twslink2pt.TWSLink2Wrap__fpCONNECT_DB_get
    if _newclass:_fpCONNECT_DB = _swig_property(_twslink2pt.TWSLink2Wrap__fpCONNECT_DB_get, _twslink2pt.TWSLink2Wrap__fpCONNECT_DB_set)
    __swig_setmethods__["_fpSQL"] = _twslink2pt.TWSLink2Wrap__fpSQL_set
    __swig_getmethods__["_fpSQL"] = _twslink2pt.TWSLink2Wrap__fpSQL_get
    if _newclass:_fpSQL = _swig_property(_twslink2pt.TWSLink2Wrap__fpSQL_get, _twslink2pt.TWSLink2Wrap__fpSQL_set)
    __swig_setmethods__["_fpSQL2"] = _twslink2pt.TWSLink2Wrap__fpSQL2_set
    __swig_getmethods__["_fpSQL2"] = _twslink2pt.TWSLink2Wrap__fpSQL2_get
    if _newclass:_fpSQL2 = _swig_property(_twslink2pt.TWSLink2Wrap__fpSQL2_get, _twslink2pt.TWSLink2Wrap__fpSQL2_set)
    __swig_setmethods__["_fpSET_EVENT_HANDLER"] = _twslink2pt.TWSLink2Wrap__fpSET_EVENT_HANDLER_set
    __swig_getmethods__["_fpSET_EVENT_HANDLER"] = _twslink2pt.TWSLink2Wrap__fpSET_EVENT_HANDLER_get
    if _newclass:_fpSET_EVENT_HANDLER = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_EVENT_HANDLER_get, _twslink2pt.TWSLink2Wrap__fpSET_EVENT_HANDLER_set)
    __swig_setmethods__["_fpSET_EVENT_HANDLER_OLE"] = _twslink2pt.TWSLink2Wrap__fpSET_EVENT_HANDLER_OLE_set
    __swig_getmethods__["_fpSET_EVENT_HANDLER_OLE"] = _twslink2pt.TWSLink2Wrap__fpSET_EVENT_HANDLER_OLE_get
    if _newclass:_fpSET_EVENT_HANDLER_OLE = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_EVENT_HANDLER_OLE_get, _twslink2pt.TWSLink2Wrap__fpSET_EVENT_HANDLER_OLE_set)
    __swig_setmethods__["_fpREM_EVENT_HANDLER"] = _twslink2pt.TWSLink2Wrap__fpREM_EVENT_HANDLER_set
    __swig_getmethods__["_fpREM_EVENT_HANDLER"] = _twslink2pt.TWSLink2Wrap__fpREM_EVENT_HANDLER_get
    if _newclass:_fpREM_EVENT_HANDLER = _swig_property(_twslink2pt.TWSLink2Wrap__fpREM_EVENT_HANDLER_get, _twslink2pt.TWSLink2Wrap__fpREM_EVENT_HANDLER_set)
    __swig_setmethods__["_fpTIME_STRING"] = _twslink2pt.TWSLink2Wrap__fpTIME_STRING_set
    __swig_getmethods__["_fpTIME_STRING"] = _twslink2pt.TWSLink2Wrap__fpTIME_STRING_get
    if _newclass:_fpTIME_STRING = _swig_property(_twslink2pt.TWSLink2Wrap__fpTIME_STRING_get, _twslink2pt.TWSLink2Wrap__fpTIME_STRING_set)
    __swig_setmethods__["_fpTIME_COMPONENT"] = _twslink2pt.TWSLink2Wrap__fpTIME_COMPONENT_set
    __swig_getmethods__["_fpTIME_COMPONENT"] = _twslink2pt.TWSLink2Wrap__fpTIME_COMPONENT_get
    if _newclass:_fpTIME_COMPONENT = _swig_property(_twslink2pt.TWSLink2Wrap__fpTIME_COMPONENT_get, _twslink2pt.TWSLink2Wrap__fpTIME_COMPONENT_set)
    __swig_setmethods__["_fpSECONDS_1970"] = _twslink2pt.TWSLink2Wrap__fpSECONDS_1970_set
    __swig_getmethods__["_fpSECONDS_1970"] = _twslink2pt.TWSLink2Wrap__fpSECONDS_1970_get
    if _newclass:_fpSECONDS_1970 = _swig_property(_twslink2pt.TWSLink2Wrap__fpSECONDS_1970_get, _twslink2pt.TWSLink2Wrap__fpSECONDS_1970_set)
    __swig_setmethods__["_fpMILLISECONDS_1970"] = _twslink2pt.TWSLink2Wrap__fpMILLISECONDS_1970_set
    __swig_getmethods__["_fpMILLISECONDS_1970"] = _twslink2pt.TWSLink2Wrap__fpMILLISECONDS_1970_get
    if _newclass:_fpMILLISECONDS_1970 = _swig_property(_twslink2pt.TWSLink2Wrap__fpMILLISECONDS_1970_get, _twslink2pt.TWSLink2Wrap__fpMILLISECONDS_1970_set)
    __swig_setmethods__["_fpSET_TIMER"] = _twslink2pt.TWSLink2Wrap__fpSET_TIMER_set
    __swig_getmethods__["_fpSET_TIMER"] = _twslink2pt.TWSLink2Wrap__fpSET_TIMER_get
    if _newclass:_fpSET_TIMER = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_TIMER_get, _twslink2pt.TWSLink2Wrap__fpSET_TIMER_set)
    __swig_setmethods__["_fpKILL_TIMER"] = _twslink2pt.TWSLink2Wrap__fpKILL_TIMER_set
    __swig_getmethods__["_fpKILL_TIMER"] = _twslink2pt.TWSLink2Wrap__fpKILL_TIMER_get
    if _newclass:_fpKILL_TIMER = _swig_property(_twslink2pt.TWSLink2Wrap__fpKILL_TIMER_get, _twslink2pt.TWSLink2Wrap__fpKILL_TIMER_set)
    __swig_setmethods__["_fpPLAY_SOUND"] = _twslink2pt.TWSLink2Wrap__fpPLAY_SOUND_set
    __swig_getmethods__["_fpPLAY_SOUND"] = _twslink2pt.TWSLink2Wrap__fpPLAY_SOUND_get
    if _newclass:_fpPLAY_SOUND = _swig_property(_twslink2pt.TWSLink2Wrap__fpPLAY_SOUND_get, _twslink2pt.TWSLink2Wrap__fpPLAY_SOUND_set)
    __swig_setmethods__["_fpREQ_FUNDAMENTAL_DATA"] = _twslink2pt.TWSLink2Wrap__fpREQ_FUNDAMENTAL_DATA_set
    __swig_getmethods__["_fpREQ_FUNDAMENTAL_DATA"] = _twslink2pt.TWSLink2Wrap__fpREQ_FUNDAMENTAL_DATA_get
    if _newclass:_fpREQ_FUNDAMENTAL_DATA = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_FUNDAMENTAL_DATA_get, _twslink2pt.TWSLink2Wrap__fpREQ_FUNDAMENTAL_DATA_set)
    __swig_setmethods__["_fpREQ_EXECUTION_DATA"] = _twslink2pt.TWSLink2Wrap__fpREQ_EXECUTION_DATA_set
    __swig_getmethods__["_fpREQ_EXECUTION_DATA"] = _twslink2pt.TWSLink2Wrap__fpREQ_EXECUTION_DATA_get
    if _newclass:_fpREQ_EXECUTION_DATA = _swig_property(_twslink2pt.TWSLink2Wrap__fpREQ_EXECUTION_DATA_get, _twslink2pt.TWSLink2Wrap__fpREQ_EXECUTION_DATA_set)
    __swig_setmethods__["_fpPARSE_XML"] = _twslink2pt.TWSLink2Wrap__fpPARSE_XML_set
    __swig_getmethods__["_fpPARSE_XML"] = _twslink2pt.TWSLink2Wrap__fpPARSE_XML_get
    if _newclass:_fpPARSE_XML = _swig_property(_twslink2pt.TWSLink2Wrap__fpPARSE_XML_get, _twslink2pt.TWSLink2Wrap__fpPARSE_XML_set)
    __swig_setmethods__["_fpGET_EXECUTION_DATA"] = _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_set
    __swig_getmethods__["_fpGET_EXECUTION_DATA"] = _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_get
    if _newclass:_fpGET_EXECUTION_DATA = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_get, _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_set)
    __swig_setmethods__["_fpGET_EXECUTION_DATA_SQL"] = _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_SQL_set
    __swig_getmethods__["_fpGET_EXECUTION_DATA_SQL"] = _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_SQL_get
    if _newclass:_fpGET_EXECUTION_DATA_SQL = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_SQL_get, _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_SQL_set)
    __swig_setmethods__["_fpGET_EXECUTION_DATA_SQL2"] = _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_SQL2_set
    __swig_getmethods__["_fpGET_EXECUTION_DATA_SQL2"] = _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_SQL2_get
    if _newclass:_fpGET_EXECUTION_DATA_SQL2 = _swig_property(_twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_SQL2_get, _twslink2pt.TWSLink2Wrap__fpGET_EXECUTION_DATA_SQL2_set)
    __swig_setmethods__["_fpQUERY_DATABASE"] = _twslink2pt.TWSLink2Wrap__fpQUERY_DATABASE_set
    __swig_getmethods__["_fpQUERY_DATABASE"] = _twslink2pt.TWSLink2Wrap__fpQUERY_DATABASE_get
    if _newclass:_fpQUERY_DATABASE = _swig_property(_twslink2pt.TWSLink2Wrap__fpQUERY_DATABASE_get, _twslink2pt.TWSLink2Wrap__fpQUERY_DATABASE_set)
    __swig_setmethods__["_fpQUERY_DATABASE_CB"] = _twslink2pt.TWSLink2Wrap__fpQUERY_DATABASE_CB_set
    __swig_getmethods__["_fpQUERY_DATABASE_CB"] = _twslink2pt.TWSLink2Wrap__fpQUERY_DATABASE_CB_get
    if _newclass:_fpQUERY_DATABASE_CB = _swig_property(_twslink2pt.TWSLink2Wrap__fpQUERY_DATABASE_CB_get, _twslink2pt.TWSLink2Wrap__fpQUERY_DATABASE_CB_set)
    __swig_setmethods__["_fpINIT_TWSLINK"] = _twslink2pt.TWSLink2Wrap__fpINIT_TWSLINK_set
    __swig_getmethods__["_fpINIT_TWSLINK"] = _twslink2pt.TWSLink2Wrap__fpINIT_TWSLINK_get
    if _newclass:_fpINIT_TWSLINK = _swig_property(_twslink2pt.TWSLink2Wrap__fpINIT_TWSLINK_get, _twslink2pt.TWSLink2Wrap__fpINIT_TWSLINK_set)
    __swig_setmethods__["_fpLOGGER"] = _twslink2pt.TWSLink2Wrap__fpLOGGER_set
    __swig_getmethods__["_fpLOGGER"] = _twslink2pt.TWSLink2Wrap__fpLOGGER_get
    if _newclass:_fpLOGGER = _swig_property(_twslink2pt.TWSLink2Wrap__fpLOGGER_get, _twslink2pt.TWSLink2Wrap__fpLOGGER_set)
    __swig_setmethods__["_fpLOGGER2"] = _twslink2pt.TWSLink2Wrap__fpLOGGER2_set
    __swig_getmethods__["_fpLOGGER2"] = _twslink2pt.TWSLink2Wrap__fpLOGGER2_get
    if _newclass:_fpLOGGER2 = _swig_property(_twslink2pt.TWSLink2Wrap__fpLOGGER2_get, _twslink2pt.TWSLink2Wrap__fpLOGGER2_set)
    __swig_setmethods__["_fpU2A"] = _twslink2pt.TWSLink2Wrap__fpU2A_set
    __swig_getmethods__["_fpU2A"] = _twslink2pt.TWSLink2Wrap__fpU2A_get
    if _newclass:_fpU2A = _swig_property(_twslink2pt.TWSLink2Wrap__fpU2A_get, _twslink2pt.TWSLink2Wrap__fpU2A_set)
    __swig_setmethods__["_fpA2U"] = _twslink2pt.TWSLink2Wrap__fpA2U_set
    __swig_getmethods__["_fpA2U"] = _twslink2pt.TWSLink2Wrap__fpA2U_get
    if _newclass:_fpA2U = _swig_property(_twslink2pt.TWSLink2Wrap__fpA2U_get, _twslink2pt.TWSLink2Wrap__fpA2U_set)
    __swig_setmethods__["_fpRISK_SET"] = _twslink2pt.TWSLink2Wrap__fpRISK_SET_set
    __swig_getmethods__["_fpRISK_SET"] = _twslink2pt.TWSLink2Wrap__fpRISK_SET_get
    if _newclass:_fpRISK_SET = _swig_property(_twslink2pt.TWSLink2Wrap__fpRISK_SET_get, _twslink2pt.TWSLink2Wrap__fpRISK_SET_set)
    __swig_setmethods__["_fpRISK_ENABLE"] = _twslink2pt.TWSLink2Wrap__fpRISK_ENABLE_set
    __swig_getmethods__["_fpRISK_ENABLE"] = _twslink2pt.TWSLink2Wrap__fpRISK_ENABLE_get
    if _newclass:_fpRISK_ENABLE = _swig_property(_twslink2pt.TWSLink2Wrap__fpRISK_ENABLE_get, _twslink2pt.TWSLink2Wrap__fpRISK_ENABLE_set)
    __swig_setmethods__["_fpRISK_TRIGGERED"] = _twslink2pt.TWSLink2Wrap__fpRISK_TRIGGERED_set
    __swig_getmethods__["_fpRISK_TRIGGERED"] = _twslink2pt.TWSLink2Wrap__fpRISK_TRIGGERED_get
    if _newclass:_fpRISK_TRIGGERED = _swig_property(_twslink2pt.TWSLink2Wrap__fpRISK_TRIGGERED_get, _twslink2pt.TWSLink2Wrap__fpRISK_TRIGGERED_set)
    __swig_setmethods__["_fpRISK_VALUE"] = _twslink2pt.TWSLink2Wrap__fpRISK_VALUE_set
    __swig_getmethods__["_fpRISK_VALUE"] = _twslink2pt.TWSLink2Wrap__fpRISK_VALUE_get
    if _newclass:_fpRISK_VALUE = _swig_property(_twslink2pt.TWSLink2Wrap__fpRISK_VALUE_get, _twslink2pt.TWSLink2Wrap__fpRISK_VALUE_set)
    __swig_setmethods__["_fpRISK_RESET"] = _twslink2pt.TWSLink2Wrap__fpRISK_RESET_set
    __swig_getmethods__["_fpRISK_RESET"] = _twslink2pt.TWSLink2Wrap__fpRISK_RESET_get
    if _newclass:_fpRISK_RESET = _swig_property(_twslink2pt.TWSLink2Wrap__fpRISK_RESET_get, _twslink2pt.TWSLink2Wrap__fpRISK_RESET_set)
    __swig_setmethods__["_fpSET_HTML_REPORT"] = _twslink2pt.TWSLink2Wrap__fpSET_HTML_REPORT_set
    __swig_getmethods__["_fpSET_HTML_REPORT"] = _twslink2pt.TWSLink2Wrap__fpSET_HTML_REPORT_get
    if _newclass:_fpSET_HTML_REPORT = _swig_property(_twslink2pt.TWSLink2Wrap__fpSET_HTML_REPORT_get, _twslink2pt.TWSLink2Wrap__fpSET_HTML_REPORT_set)
    __swig_setmethods__["_fpTEST_1"] = _twslink2pt.TWSLink2Wrap__fpTEST_1_set
    __swig_getmethods__["_fpTEST_1"] = _twslink2pt.TWSLink2Wrap__fpTEST_1_get
    if _newclass:_fpTEST_1 = _swig_property(_twslink2pt.TWSLink2Wrap__fpTEST_1_get, _twslink2pt.TWSLink2Wrap__fpTEST_1_set)
TWSLink2Wrap_swigregister = _twslink2pt.TWSLink2Wrap_swigregister
TWSLink2Wrap_swigregister(TWSLink2Wrap)

def TWSLink2Wrap_InstanceCount():
  return _twslink2pt.TWSLink2Wrap_InstanceCount()
TWSLink2Wrap_InstanceCount = _twslink2pt.TWSLink2Wrap_InstanceCount
cvar = _twslink2pt.cvar

# This file is compatible with both classic and new-style classes.


